apiVersion: v1
kind: Secret
metadata:
  name: demo-secrets
  namespace: attachments-demo
type: Opaque
stringData:
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app
  POSTGRES_DB: app

  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: minio12345

  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
